data_directory: ../data/
image_paths: ../data/train001/
output_path: ../outputs/

dataset:
  csv_name: ../data/training_data_2000.csv
  num_each_class: 1000
  split:
    ratio_train: 0.8
    ratio_valid: 0.1
    ratio_test: 0.1

dataloader:
  batch_size: 32

device: cpu
seed: 42
training:
  num_epochs: 100
  optimizer:
    learning_rate: 0.001
    momentum: 0.9

