data_directory: ../data/
image_paths: ../data/train001/
output_path: ../outputs/

dataset:
  csv_name: ../data/max_images.csv
  num_each_class: 13500
  split:
    ratio_train: 0.8
    ratio_valid: 0.1
    ratio_test: 0.1

model:
  pretrained: True
  requires_grad: True
  add_layers: True

model_to_test:
  pretrained: False
  requires_grad: False
  add_layers: True

dataloader:
  batch_size: 32

device: cpu
seed: 42
training:
  num_epochs: 30
  optimizer:
    learning_rate: 0.0001
    momentum: 0.9

