data_directory: ../data/
image_paths: ../data/train001/
output_path: ../outputs/

dataset:
  csv_name: ../data/max_images.csv
  num_each_class: 13500
  split:
    ratio_train: 1.0
    ratio_valid: 0.0
    ratio_test: 0.0

model:
  pretrained: True
  requires_grad: True
  add_layers: True

dataloader:
  batch_size: 32

device: cpu
seed: 42
training:
  num_epochs: 1
  optimizer:
    learning_rate: 0.001
    momentum: 0.9

