data_directory: ../data/
image_paths: ../data/train001/
output_path: ../outputs/

dataset:
  csv_name: ../data/balanced_5262.csv
  num_each_class: 5262
  split:
    ratio_train: 0.8
    ratio_valid: 0.1
    ratio_test: 0.1

model:
  pretrained: True
  requires_grad: True
  add_layers: True

model_to_test:
  pretrained: False
  requires_grad: False
  add_layers: True

dataloader:
  batch_size: 32

device: cpu
seed: 42
training:
  num_epochs: 50
  optimizer:
    learning_rate: 0.0001
    momentum: 0.9

attacks:
  epsilons: [0, 0.2/255, 1/255, 2/255, 3/255, 4/255, 5/255]

